### ISSUE TITLE
Next/Previous Tab action uses original tab order

### ISSUE THREAD

**Issue by ashiguruma** [patrik-piskay/hyperterm-tabs#1]
After reordering switching tabs using the 'Next/Previous Tab' keyboard shortcuts (`alt+cmd+left` and `alt+cmd+right`) uses the order in which the tabs were originally opened.

![hyperterm-tabs-bug](https://cloud.githubusercontent.com/assets/863711/17737315/824154ee-6484-11e6-9ba1-d7261628400f.gif)

**Comment by ashiguruma** [comment]
Happy to take a look into this and PR if needed.

**Comment by patrik-piskay** [comment]
Hi @ashiguruma,

thanks for reporting, happy to accept a PR 👍 

I've not realised it as I am not using next/previous tab shortcut, but an easy fix would be altering the `UI_MOVE_LEFT` and `UI_MOVE_RIGHT` actions to use `sessionsOrdered` array (created by this plugin) instead of HyperTerm's `sessions` object. But...

I think we should try to get rid of `sessionOrdered` array and instead just use `sessions` for reordering tabs. That way, next/previous tab shortcut will keep working without any change and it would be more "future-proof" as we won't depend on our custom data structure.

If you fancy taking a look and refactor `sessions` usage, let me know, otherwise I will tackle this problem tonight.

**Comment by ashiguruma** [comment]
Hi @patrik-piskay My update will likely be slower than yours so if you really want to get this fixed ASAP then please go ahead. If you're in no hurry I'd be happy to take a look at this as it'll be a useful learning experience.

When suggesting using the `sessions` object do you mean modify the order of the session keys in sessions and return the new state? That seems like the sensible option.

**Comment by patrik-piskay** [comment]
Exactly. But as you cannot just change the order of keys in an object, it think you will need to determine the correct order of session `uid`s  first and then recreate a new session object from the old one by placing the sessions in in the new order. Hopefully that would work.

Let me know if you have any troubles along the way

**Comment by patrik-piskay** [comment]
Hi @ashiguruma, have you made any progress on this?

**Comment by ashiguruma** [comment]
Managed to get the session object to successfully reorder but it's been rather buggy. I'm not yet familiar enough with the setup and have struggled to debug my issues. I'll try and push a WIP this evening.

**Comment by ashiguruma** [comment]
Hi @patrik-piskay. I've pushed an update to my fork. The reordering using the sessions property appears to work but the update to the state seems to cause bugs. Dragging a tab to a lower index causes it to close and dragging to a higher index blanks the tab but keeps it on screen.

I get the impression that the state needs to be updated in some other manner but I'm not yet up to speed with the immutable setup of hyperterm plugins. Any help would be greatly appreciated.

**Comment by patrik-piskay** [comment]
Hi @ashiguruma, I don't think I will have much time next couple of days so if you want to continue digging deeper into the problem, please go ahead. 

But If you feel like you are stuck in the next few days, I will even take a PR doing it the simpler way (described in my first comment) so we fix the issue and than we can have more time trying to do it the proper way.

Thanks for the effort!

**Comment by patrik-piskay** [comment]
Hi @ashiguruma, any progress on this? I'd like to get this fixed ASAP, so I'd now take even the simpler solution. Or just let me know and I'll do it!

**Comment by ashiguruma** [comment]
Hey @patrik-piskay, I've not been able to get either method sorted yet due to limited time and a lack of knowledge. I had another stab at reordering using the `sessionsOrdered` array but the state change to `activeUid` seems not to take effect.

Feel free to take a look at [the branch on my fork](https://github.com/ashiguruma/hyperterm-tabs/commit/17cb889d6852e7918f04baea125f37383dd20796). Clearly I need to understand the HyperTerm architecture a little better.

**Comment by patrik-piskay** [comment]
Hi @ashiguruma, finally I've returned from holiday and took a look at this issue. Please see https://github.com/patrik-piskay/hyperterm-tabs/commit/6af19290376d70f142d70fb404a40932b5fb30d5 in my custom branch. Unfortunately I won't be able to test on Mac any time soon, can you checkout the fix branch and test locally if it fixes the issue for you? (It works on my Ubuntu, just to make sure it does on Mac as well). If it does, I will merge and release it. Thanks!

**Comment by ashiguruma** [comment]
Hey Patrik, it works perfectly on OS X (10.11.3). Thanks for sorting that out.

**Comment by patrik-piskay** [comment]
Great!
