### ISSUE TITLE
Drag & drop not working with Hyper v1.x on MacOS Sierra

### ISSUE THREAD

**Issue by zackehh** [patrik-piskay/hyperterm-tabs#12]
So... I dunno how to find out why, so let me know if you need me to do anything to investigate :)

The shortcuts work, but dragging & dropping still just drags the entire Hyper window around; not sure if there's something I need to toggle for that etc?

Shortcuts work great though.

**Comment by patrik-piskay** [comment]
Not at the moment unfortunatelly, it's not possible to drag&drop tabs because of the change made in Hyper's code - there is an issue https://github.com/zeit/hyper/issues/911 opened for this.
