### ISSUE TITLE
Does not work with Hyper 2.0.0-canary.11

### ISSUE THREAD

**Issue by aleksijohansson** [patrik-piskay/hyperterm-tabs#19]
Hey!

Just wanted to let you know that when I briefly visited the new 2.0 canary 11 this plugin was not working. I really like the plugin and it's fixing one last issue which kept me away from Hyper. I hope to see it working eventually in 2.0 too. Keep up the good work!

**Comment by patrik-piskay** [comment]
The plan is to support 2.0 too of course, but that's possible only when it's released (we can't support both stable and canary afaik). It seems 2.0 stable will be released soon though, so it's a good time to start looking into it!

**Comment by aleksijohansson** [comment]
Glad to hear, looking forward to it!

**Comment by patrik-piskay** [comment]
I have a working version here https://github.com/patrik-piskay/hyperterm-tabs/tree/hyper-2-update

You might want to start using it by replacing the code in your hyper node_modules, until Hyper 2 stable is released. 

Also, I wasn't able to keep using the old shortcuts, by default `alt+left/right` work for moving tabs, but you are free to define your own shortcuts too -> [readme](https://github.com/patrik-piskay/hyperterm-tabs/blob/hyper-2-update/readme.md#usage)

**Comment by joncalhoun** [comment]
hi @patrik-piskay - whats the easiest way to install that branch? Not a huge npm user so not sure on the easiest way to do it with hyper.

**Comment by patrik-piskay** [comment]
I've just published it on npm with the `next` tag, so if you are on Hyper canary, you can change your plugins config from `hyperterm-tabs` to `hyperterm-tabs#next` an it should start working after restart.

**Comment by aleksijohansson** [comment]
@patrik-piskay Using `hyperterm-tabs#next` works great with Hyper `2.0.0-canary.14` on macOS High Sierra 10.13.3, but it does not work at all with the same Hyper canary on Windows 10. Any ideas for fixing it for Windows?

**Comment by dbkaplun** [comment]
I can reproduce, thanks for working on this!

**Comment by vincentwongso** [comment]
`hyperterm-tabs#next` doesn't seems to work on hyper v2.0.0 stable on MacOS

**Comment by patrik-piskay** [comment]
Should be fixed now, can you verify? (_probably need to remove and add the package again?_) btw no need for the `#next`, Hyper v2 compatible version is published with the latest tag now, so installing `hyperterm-tabs` should get you the right version now
