### ISSUE TITLE
Bug with hover state when moving

### ISSUE THREAD

**Issue by henrikdahl** [patrik-piskay/hyperterm-tabs#2]
If you have 3 tabs .[1].[2].[3]. and you move [2] to .[1] then you'll sometimes have the old [1] that becomes [2] have a hover state even though you're not hovering it. Simply put a hover background-color and you can easily reproduce it.

Not sure why it gets the hover property to begin with or keeps it afterwards.

**Comment by patrik-piskay** [comment]
Hi @henrikdahl, unfortunately currently I have no possibility of testing this on Mac myself. I've tried it on Linux and I couldn't reproduce the issue - hover state was correct (the tab with cursor over it had the hover style applied).

You can investigate yourself and send a PR that fixes it, or I will try to reproduce it again when I have a chance with Mac.

Thanks!

**Comment by henrikdahl** [comment]
Here's an example of what I mean. I'm gonna try to find out more about why it happens. It's almost as if when you drag a tab and moseouver another one, it gets the mouseover state but never mouseout.

![tabs](https://cloud.githubusercontent.com/assets/1430576/18349610/7c3d593a-75d2-11e6-84fe-5a869ea93c98.gif)

**Comment by henrikdahl** [comment]
The very same bug exists in Atom on OS X as well. I believe it's related to electron. Hence I'm closing this.
