### ISSUE TITLE
Custom keymappings doesn’t work on MacOS

### ISSUE THREAD

**Issue by jeanfredrik** [patrik-piskay/hyperterm-tabs#20]
I have put these lines under `config` in .hyper.js.

```js
hyperTabsMove: {
  moveLeft: ['ctrl+left', 'command+left', 'alt+left', 'alt+shift+left'],
  moveRight: ['ctrl+right', 'command+right', 'alt+right', 'alt+shift+right'],
}
```

- `ctrl+left/right` does nothing.
- `command+left/right` doesn’t move the tab but moves the cursor to beginning/end of line (this is a default mapping in Hyper).
- `alt+left/right` works as before (this is the default mapping from the plugin).
- `alt+shft+left/right` prints `;4D` and `;4C` respectively _and_ moves the tab

I want to use `ctrl` or `command` but those doesn’t work. The other ones are just for reference. Is this a problem with this plugin, Hyper, or MacOS?

**Comment by patrik-piskay** [comment]
Hey @jeanfredrik, the issue with these is OS related. some shortcuts work on Windows, but not on Linux/Mac. Some work on Mac but not on the other 2 platforms. It's annoying but I couldn't find any shortcut that would be reasonable AND worked on all platforms.

You are able to configure this yourself, but again, the result will depend on your OS. As you mentioned, on Mac some of these don't do anything, or print something to the output. I'm afraid there is nothing that could be done from the plugin point of view 🤷‍♂️(although having `alt+right/left` work on Mac is pretty good 😄)
