### ISSUE TITLE
⌘1 ⌘2 ordering messed up

### ISSUE THREAD

**Issue by henrikdahl** [patrik-piskay/hyperterm-tabs#4]
I'm not sure this is a bug but ⌘1 ⌘2 ⌘3 ordering gets messed up after moving around tabs. For example ⌘2 in my opinion should always take you to the second tab, not the 5th because you switched 5 and 2 before?

**Comment by patrik-piskay** [comment]
Hey, got it, I will fix it tonight :+1:

**Comment by ashiguruma** [comment]
Hey @patrik-piskay I have a fix for this if you're interested.

**Comment by patrik-piskay** [comment]
Sure!

**Comment by patrik-piskay** [comment]
@henrikdahl, the issue should be fixed now by https://github.com/patrik-piskay/hyperterm-tabs/pull/5
