### ISSUE TITLE
Tabs not rearranging

### ISSUE THREAD

**Issue by kbrock** [patrik-piskay/hyperterm-tabs#7]
Hello,

I'm hoping you can point me to where I'm doing this wrong, but I can't figure how to rearrange the tabs.

1. I go to the title in the tab
2. click and hold the left mouse button (only mouse button on a mac)
3. Move the mouse to the right
4. The window moves to the right
5. expecting the tab to move and the window to remain still.

Questions:

1. Do I need to press a special key when clicking the mouse button?
2. Do I need to move the mouse in a special direction after clicking the mouse button?
3. Do I need to click in a special location on the tab to enable this functionality?

I'm using hyper on mac along with a few plugins. When I rearrange the tabs, I end up moving the window.

Any pointers would be great.
Thanks,
Keenan

---
On a mac running sierra and bash. Tried earlier with hyperterm.app, and again using the recent hyper.app.

current plugins:
```
    'hyperterm-title', // respect linux titles
    'hypercwd', // open tabs in the current directory
    'hyperterm-tab-icons', // icon in the tab bar of current process - (not necessary)
//    "hyperterm-alternatescroll", // scrolling is inside program (vs scroll vi off the screen)
    'hyperterm-tabs', //drag and drop tabs
    'hyperterm-monokai'
```

**Comment by patrik-piskay** [comment]
Hi,

you should be able to drag&drop just by clicking and moving the tab.

Why it is not working now is described in https://github.com/patrik-piskay/hyperterm-tabs/issues/6, I am currently working on a fix.

I'll close this and keep updating in https://github.com/patrik-piskay/hyperterm-tabs/issues/6.

**Comment by kbrock** [comment]
thanks so much
