### ISSUE TITLE
Doesn't seem to work with Hyper 1.0.0 on Windows

### ISSUE THREAD

**Issue by stereokai** [patrik-piskay/hyperterm-tabs#9]
And this is what the console shows:

![drag](https://cloud.githubusercontent.com/assets/2685357/21163396/811d2452-c19b-11e6-957b-8352f81bfdd6.PNG)

Where does the `el` object comes from?

**Comment by patrik-piskay** [comment]
Thanks for reporting! I only managed to test on Mac, I'll do my best to test on Windows and Linux soon. In the meantime I suggest disabling the plugin if it breaks Hyper for you.

`this.el` is being set [here](https://github.com/patrik-piskay/hyperterm-tabs/blob/master/index.js#L377) as a React's callback ref.

**Comment by stereokai** [comment]
@patrik-piskay please let me know if I can help.

**Comment by patrik-piskay** [comment]
Hey @stereokai, I just tested on Win10 and everything ran normal. Except shortcuts :D So I just added a `ctrl+shift+alt+arrows` to the current `shift+alt+arrows`. With this, `ctrl+shift+alt+arrows` worked for me on Windows.

**Comment by jonathandelgado** [comment]
I'm still getting the same `Uncaught TypeError: Cannot read property 'document_' of undefined` error on version 1.3.2, Windows 10 x64

Did some basic debugging, `this.el` is set, but there isn't a `this.el.term` set when it gets [to line 365](https://github.com/patrik-piskay/hyperterm-tabs/blob/1a2b32464ac22c29be431d4f9c8dd171d0b81731/index.js#L365)

**Comment by patrik-piskay** [comment]
I'll try to reproduce the issue this Wednesday when I get my hands on a real Win (not only VM Win).

**Comment by stereokai** [comment]
@patrik-piskay thanks man! I'm looking forward to your update! :)

**Comment by patrik-piskay** [comment]
Hi @stereokai @jonathandelgado , I tested on fresh install of Hyper and hyperterm-tabs@1.3.3 on Win10 64bit and no issue. If you still experience the issue, could you please debug more, ie by wrapping the logic from line 365 to an `if` statement (`if (this.el.term) {...}`) and see if it fixes the issue? Maybe the `el.term` is not set on initial render but then `el` gets updated.

**Comment by Stanzilla** [comment]
```
bundle.js:1 Error: Cannot find module 'C:\Users\Benjamin\.hyper_plugins\node_modules\hyperterm-tabs'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\Benjamin\AppData\Local\hyper\app-1.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at de.plugins.concat.map.ge (file:///C:/Users/Benjamin/AppData/Local/hyper/app-1.2.1/resources/app/dist/bundle.js:1:8503)
    at Array.map (native)
    at ie (file:///C:/Users/Benjamin/AppData/Local/hyper/app-1.2.1/resources/app/dist/bundle.js:1:8457)
    at Object.<anonymous> (file:///C:/Users/Benjamin/AppData/Local/hyper/app-1.2.1/resources/app/dist/bundle.js:1:9992)
    at __webpack_require__ (file:///C:/Users/Benjamin/AppData/Local/hyper/app-1.2.1/resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///C:/Users/Benjamin/AppData/Local/hyper/app-1.2.1/resources/app/dist/bundle.js:45:375898)
```

**Comment by patrik-piskay** [comment]
Looks like Hyper did not install `hyperterm-tabs` before trying to access it. Usually restarting Hyper solves it. Can you confirm?

**Comment by Stanzilla** [comment]
Nah, but I guess hpm is currently not working https://github.com/zeit/hpm/issues/72

![chrome_2017-02-20_13-51-04](https://cloud.githubusercontent.com/assets/75278/23125776/bde52d22-f773-11e6-987e-3369561d53eb.png)

just refuses to install it

**Comment by harrywincup** [comment]
@Stanzilla Not sure if it's the same issue for you, but I couldn't get any plugins to install until I set `shell: '/bin/bash'` inside `~/.hyper.js` on macOS Sierra. Now they install fine during the hot reload

**Comment by Stanzilla** [comment]
Yes, thank you. It was this https://github.com/zeit/hyper/pull/1516

**Comment by rosszurowski** [comment]
Just wanted to chime in and say I got the same error on macOS Sierra with Hyper 1.3.1, and my `shell` set inside `~/.hyper.js`.

<img width="875" alt="screen shot 2017-03-24 at 19 59 54" src="https://cloud.githubusercontent.com/assets/303731/24318961/7873602a-10cc-11e7-8b14-e2bd30244e1f.png">


I'm not sure if this is related to the original issue, but in my testing, it seemed directly tied to whether or not I had a Bash escaped string to set the terminal title, like so:

```
# the `\[\033]0;` to `\007\]`
export PS1="\[\033]0;\W\007\]$ "
```

Removing the string from my `PS1` solved the problem, adding it back brought the issue back. I ended up uninstalling hyperterm-tabs, which also resolved the issue.

**Comment by garethweaver** [comment]
I'm having this happen on OSX, tried removing everything from my PS1 in `.bash_profile` and still got `Cannot read property of 'doucment_' of undefined`

**Comment by patrik-piskay** [comment]
Is there anyone who experiences the issue who would like to dig into it and possibly contribute with a fix?

**Comment by WaveHack** [comment]
@patrik-piskay I'll see what I can do. I'm experiencing this issue on Hyper 1.3.3 on Windows 10 x64 using WSL as shell.

**Comment by WaveHack** [comment]
There we go: #15
